fragment ServiceInstance on ServiceInstance {
  id
  instanceId
  release {
    version 
    service {
      id
      identifier
    }
  }

  allowedUsers {
    ...ListUser
  }
  deniedUsers {
    ...ListUser
  }
  allowedGroups {
    ...ListGroup
  }
  deniedGroups {
    ...ListGroup
  }
  mappings {
    ...ListServiceInstanceMapping
  }
  logo {
    presignedUrl
  }
}

fragment ListServiceInstance on ServiceInstance {
  id
  instanceId
  allowedUsers {
    ...ListUser
  }
  deniedUsers {
    ...ListUser
  }
}
